version: "3.9"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  report_bot:
    image: bot-report:latest
    container_name: bot-report
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
        # reservations:
        #   cpus: "0.25"
        #   memory: 100M
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    logging: *logging